apiVersion: apps/v1
kind: Deployment
metadata:
  name: negotiator-v3
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      service: negotiator-v3-service
  template:
    metadata:
      labels:
        service: negotiator-v3-service
    spec:
      containers:
      - name: negotiator-v3
        image: bbmrieric/negotiator:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 8081
        env:
        - name: PROFILE
          value: "debug"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://negotiator-v3-db-service:5432/negotiator"
        - name: SPRING_DATASOURCE_USERNAME
          value: "negotiator"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: negotiator-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_DATASOURCE_INITIALIZE
          value: "false"
        - name: SPRING_FLYWAY_ENABLED
          value: "true"
        - name: SPRING_FLYWAY_USER
          value: "negotiator"
        - name: SPRING_FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: negotiator-secrets
              key: SPRING_FLYWAY_PASSWORD
        - name: SPRING_FLYWAY_URL
          value: "jdbc:postgresql://negotiator-v3-db-service:5432/negotiator"
        - name: NEGOTIATOR_FRONTENDURL
          value: "https://negotiator.eucaim.cancerimage.eu"
        - name: SERVER_FORWARD_HEADERS_STRATEGY
          value: "framework"
        - name: NEGOTIATOR_AUTHORIZATION_CLAIM
          value: "eduperson_entitlement"
        - name: NEGOTIATOR_AUTHORIZATION_ADMINCLAIMVALUE
          value: "urn:geant:bbmri-eric.eu:res:role_admin#perun.bbmri-eric.eu"
        - name: NEGOTIATOR_AUTHORIZATION_RESEARCHERCLAIMVALUE
          value: "urn:geant:bbmri-eric.eu:res:role_researcher#perun.bbmri-eric.eu"
        - name: NEGOTIATOR_AUTHORIZATION_RESOURCECLAIMPREFIX
          value: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory:"
        - name: NEGOTIATOR_AUTHORIZATION_BIOBANKERCLAIMVALUE
          value: "urn:geant:bbmri-eric.eu:res:role_representative#perun.bbmri-eric.eu"
        - name: NEGOTIATOR_AUTHORIZATION_SUBJECTCLAIM
          value: "sub"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_ID
          #value: "a15a95d1-b251-4f12-b608-76ec02c68010"
          value: "8c902458-3640-4418-94b4-8f4b7f338957"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_SECRET
          #value: "33a1c16e-fedb-494a-9bdb-fc79fbbb19e63156db50-89ce-46be-ba24-8c8b362f2344"
          value: "fd0bf732-e828-41e6-8f73-5c2abed99708f0a1ef98-8edb-4ed5-8e08-10fe65c663fd"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_INTROSPECTION_URI
          value: "https://login.bbmri-eric.eu/oidc/introspect"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES
          value: "a15a95d1-b251-4f12-b608-76ec02c68010"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
          #value: "https://login.aai.lifescience-ri.eu/oidc/"
          value: "https://login.bbmri-eric.eu/oidc/"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI
          value: "https://login.bbmri-eric.eu/oidc/jwk"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_USERINFOURI
          value: "https://login.bbmri-eric.eu/oidc/userinfo"
        - name:  NEGOTIATOR_MOLGENIS_URL
          value: "https://catalogue.eucaim.cancerimage.eu"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_TYPE
          value: "at+jwt"
        - name: ACTIVE_THEME
          value: "eucaim"
        - name: ACTIVE_LOGOS
          value: "eucaim"
        - name: SPRING_MAIL_HOST
          value: "smtp://smtp.gmail.com"
        - name: SPRING_MAIL_PORT
          value: "587"
        - name: SPRING_MAIL_USERNAME
          value: "eucaim.negotiator@gmail.com"
        - name: SPRING_MAIL_PASSWORD
          value: "EUC41MT0k3n"
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
          value: "true"
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
          value: "true"
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
