apiVersion: apps/v1
kind: Deployment
metadata:
  name: negotiator-v3
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      service: negotiator-v3-service
  template:
    metadata:
      labels:
        service: negotiator-v3-service
    spec:
      containers:
      - name: negotiator-v3
        image: bbmrieric/negotiator:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 8080
        env:
        - name: PROFILE
          value: "debug"
        - name: SPRING_DATASOURCE_URL
          #value: "jdbc:postgresql://147.251.253.214:5432/negotiator"
          # SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/negotiator
          value: "jdbc:postgresql://negotiator-v3-db-service:5432/negotiator"
          #value: "jdbc:postgresql://postgres:5432/negotiator"
        - name: SPRING_DATASOURCE_USERNAME
          value: "negotiator"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "negotiator"
        - name: SPRING_DATASOURCE_INITIALIZE
          value: "false"
        - name: SPRING_FLYWAY_ENABLED
          value: "true"
        - name: SPRING_FLYWAY_USER
          value: "negotiator"
        - name: SPRING_FLYWAY_PASSWORD
          value: "negotiator" # Directly specify the password here
        - name: SPRING_FLYWAY_URL
          value: "jdbc:postgresql://negotiator-v3-db-service:5432/negotiator"
          #value: "jdbc:postgresql://postgres:5432/negotiator"
        - name: NEGOTIATOR_FRONTENDURL
          value: "https://negotiator.eucaim.cancerimage.eu"
        - name: SERVER_FORWARD_HEADERS_STRATEGY
          value: "framework"
        - name: NEGOTIATOR_AUTHORIZATION_CLAIM
          value: "eduperson_entitlement"
        - name: NEGOTIATOR_AUTHORIZATION_ADMINCLAIMVALUE
          value: "urn:geant:bbmri-eric.eu:res:role_admin#perun.bbmri-eric.eu"
        - name: NEGOTIATOR_AUTHORIZATION_RESEARCHERCLAIMVALUE
          value: "urn:geant:bbmri-eric.eu:res:role_researcher#perun.bbmri-eric.eu"
        - name: NEGOTIATOR_AUTHORIZATION_RESOURCECLAIMPREFIX
          value: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory:"
        - name: NEGOTIATOR_AUTHORIZATION_BIOBANKERCLAIMVALUE
          value: "urn:geant:bbmri-eric.eu:res:role_representative#perun.bbmri-eric.eu"
        - name: NEGOTIATOR_AUTHORIZATION_SUBJECTCLAIM
          value: "sub"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_ID
          value: "a15a95d1-b251-4f12-b608-76ec02c68010"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_SECRET
          value: "33a1c16e-fedb-494a-9bdb-fc79fbbb19e63156db50-89ce-46be-ba24-8c8b362f2344"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_INTROSPECTION_URI
          value: "https://login.bbmri-eric.eu/oidc/introspect"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES
          value: "https://negotiator.eucaim.cancerimage.eu"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
          value: "https://login.bbmri-eric.eu/oidc/"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI
          value: "https://login.bbmri-eric.eu/oidc/jwk"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_USERINFOURI
          value: "https://login.bbmri-eric.eu/oidc/userinfo"
        - name:  NEGOTIATOR_MOLGENIS_URL
          value: "https://bbmritestnn.gcc.rug.nl"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_TYPE
          value: "at+jwt"
        resources:
          requests:
            cpu: "125m"
            memory: "512Mi"
          limits:
            cpu: "0.2"
            memory: "1Gi"
