apiVersion: apps/v1
kind: Deployment
metadata:
  name: negotiator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: negotiator-frontend
  template:
    metadata:
      labels:
        app: negotiator-frontend
    spec:
      containers:
      - name: negotiator-frontend
        image: bbmrieric/negotiator-frontend:1.4
        imagePullPolicy: Always
        env:
          - name: AUTH_URL
            value: "https://login.bbmri-eric.eu/oidc"
          - name: CLIENT_ID
            value: "a15a95d1-b251-4f12-b608-XXXX"
          - name: REDIRECT_URI
            value: "https://negotiator.eucaim.cancerimage.eu/logged-in"
          - name: LOGOUT_URI
            value: "https://negotiator.eucaim.cancerimage.eu"
          - name: API_RESOURCES
            value: "https://negotiator.eucaim.cancerimage.eu"
          - name: ACTIVE_THEME
            value: "eucaim"
          - name: ACTIVE_LOGOS
            value: "eucaim"
        ports:
          - containerPort: 8080
