apiVersion: v1
kind: Secret
metadata:
  name: eucaim-broker-eucaim-cancerimage-eu-priv-pem
data:
  eucaim.broker.eucaim.cancerimage.eu.priv.pem: your-proxy-private-pem-cert-enc-base64

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: beam-proxy-deployment
  labels:
    app: beam-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beam-proxy
  template:
    metadata:
      labels:
        app: beam-proxy
    spec:
      containers:
      - name: beam-proxy
        image: samply/beam-proxy:develop
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 2Gi
          limits: 
            cpu: 1
            memory: 2Gi
        env:
        - name: APP_focus_KEY
          valueFrom: 
            secretKeyRef:
              name: spot-beam-secret
              key: BEAM_SECRET
        - name: BROKER_URL
          value: https://broker.eucaim.cancerimage.eu
        - name: PROXY_ID
          value: eucaim.broker.eucaim.cancerimage.eu
        - name: PRIVKEY_FILE
          value: /run/secrets/eucaim.broker.eucaim.cancerimage.eu.priv.pem
        - name: BIND_ADDR
          value: 0.0.0.0:8081
        volumeMounts:
        - mountPath: /run/secrets
          readOnly: true
          name: certs
      volumes:
      - name: certs
        projected:
          sources:
          - secret:
              name: eucaim-broker-eucaim-cancerimage-eu-priv-pem
          - secret:
              name: root-crt-pem

---

apiVersion: v1
kind: Service
metadata:
  name: beam-proxy-service
  labels:
    app: beam-proxy
spec:
  selector:
    app: beam-proxy
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      
---