
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: broker-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  tls:
    - hosts:
        - broker.eucaim.cancerimage.eu
      secretName: broker.eucaim.cancerimage.eu
  rules:
    - host: broker.eucaim.cancerimage.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: broker-service
                port:
                  number: 8080

---

apiVersion: v1
kind: Secret
metadata:
  name: pki-secret
data:
  pki.secret: your_pki_secret_enc_base64

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: samply/beam-broker:main
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 4Gi
          limits: 
            cpu: 1
            memory: 4Gi
        env:
        - name: RUST_LOG
          value: debug
        - name: PKI_ADDRESS
          value: http://vault:8200
        - name: no_proxy
          value: vault
        - name: NO_PROXY
          value: vault
        - name: BROKER_URL
          value: https://broker.eucaim.cancerimage.eu
        - name: PRIVKEY_FILE
          value: /run/secrets/broker.priv.pem
        volumeMounts:
        - mountPath: /run/secrets
          readOnly: true
          name: certs
      volumes:
      - name: certs
        projected:
          sources:
          - secret:
              name: pki-secret
          - secret:
              name: root-crt-pem
          - secret:
              name: broker-priv-pem

---

apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    app: broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
