
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: explorer-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  tls:
    - hosts:
        - explorer.eucaim.cancerimage.eu
      secretName: explorer.eucaim.cancerimage.eu
  rules:
    - host: explorer.eucaim.cancerimage.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lens-service
                port:
                  number: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lens-deployment
  labels:
    app: lens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lens
  template:
    metadata:
      labels:
        app: lens
    spec:
      containers:
      - name: lens
        resources:
          requests:
            cpu: 250m
            memory: 2Gi
          limits: 
            cpu: 1
            memory: 2Gi
        imagePullPolicy: Always
        image: docker.verbis.dkfz.de/eucaim/lens:eucaim

---

apiVersion: v1
kind: Service
metadata:
  name: lens-service
  labels:
    app: lens
spec:
  selector:
    app: lens
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
---