kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-resources-full-access
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-sa-role-binding
subjects:
  - kind: ServiceAccount
    name: admin-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-resources-full-access

