apiVersion: v1
kind: Pod
metadata:
  name: console
spec:
  restartPolicy: Never
  containers:
  - name: alpine
    image: alpine
    command: [ "/bin/ash" ]
    args: ["-c", "tail -f /dev/null"]
    
    volumeMounts:
        - name: nfs
          mountPath: "/my-nfs"
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: postgres-data-pvc
