kind: PersistentVolume
apiVersion: v1
metadata:
  name: mockup-vol
  labels:
    type: local
spec:
  storageClassName: nfs-mockup
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 150M
  accessModes:
    - ReadWriteMany
  nfs:
    server: X.X.X.X
    path: /mnt/nfs_share/mockup
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mockup-vol-pvc
spec:
  storageClassName: nfs-mockup
  volumeName: mockup-vol
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16M
