apiVersion: v1
kind: ServiceAccount
metadata:
  name: eucaim-user
  namespace: eucaim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eucaim-rb
  namespace: eucaim
subjects:
- kind: ServiceAccount
  name: eucaim-user
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: eucaim-token
  namespace: eucaim
  annotations:
    kubernetes.io/service-account.name: eucaim-user
type: kubernetes.io/service-account-token




