kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor-harbor-pvc
  namespace: harbor 
spec:
  storageClassName: nfs-harbor
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi

