apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ontology
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: ontologypv
