apiVersion: v1
kind: Secret
metadata:
  name: api-keys
stringData:
  FOCUS_API_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  DATASET_SERVICE_AUTH_HEADER: "Secret XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
type: Opaque
