apiVersion: apps/v1
kind: Deployment
metadata:
  name: beam-proxy-deployment
  labels:
    app: beam-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beam-proxy
  template:
    metadata:
      labels:
        app: beam-proxy
    spec:
      containers:
      - name: beam-proxy
        image: samply/beam-proxy:develop
        env:
        - name: APP_focus_KEY
          valueFrom: 
            secretKeyRef:
              name: app1-key
              key: APP1_KEY
        - name: BROKER_URL
          value: https://broker.eucaim.cancerimage.eu
        - name: PROXY_ID
          value: chaimeleon.broker.eucaim.cancerimage.eu
        - name: PRIVKEY_FILE
          value: /run/secrets/proxy.pem
        - name: BIND_ADDR
          value: 0.0.0.0:8081
        volumeMounts:
        - mountPath: /run/secrets
          readOnly: true
          name: certs
        ports:
          - containerPort: 8081
            name: pport
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
      volumes:
      - name: certs
        projected:
          sources:
          - secret:
              name: proxy-pem
          - secret:
              name: root-crt-pem
      priorityClassName: core-services
      nodeSelector: 
        chaimeleon.eu/target: core-services

---
apiVersion: v1
kind: Service
metadata:
  name: beam-proxy-service
  labels:
    app: beam-proxy
spec:
  selector:
    app: beam-proxy
  ports:
    - protocol: TCP
      port: 8081
      targetPort: pport
