apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-rabbitmq-config
data:
  rabbitmq.conf: |
    # Enable subpath
    management.path_prefix = /orchestrator-rabbitmq-admin
    # Disabte non SSL connection
    listeners.tcp = none

    # Enable AMQPS
    listeners.ssl.default = 5671
    ssl_options.cacertfile = /etc/rabbitmq/certs/rootCA_cert.pem
    ssl_options.certfile = /etc/rabbitmq/certs/server_cert.pem
    ssl_options.keyfile = /etc/rabbitmq/certs/server_key.pem
    ssl_options.verify = verify_peer
    ssl_options.fail_if_no_peer_cert = true
