apiVersion: v1
kind: Service
metadata:
  name: orchestrator-rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5671
    targetPort: 5671
    protocol: TCP
    name: api
    nodePort: 5671
  selector:
    app: orchestrator-rabbitmq