apiVersion: apps/v1
kind: Deployment
metadata:
  name: negotiator
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      service: negotiator
  template:
    metadata:
      labels:
        service: negotiator
    spec:  
      containers:
      - name: negotiator
        #        image: bbmricz/negotiator:latest
        #image: eucaim.cancerimage.eu:10443/library/negotiator-v2-eucaim@sha256:311aa9f827aacf0129f70055082ab4c90814ce0b5f039b8e9d53c3f25f5a91e0
        image: eucaim.cancerimage.eu:10443/library/negotiator-v2-eucaim:2.8.3
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 8080
        env: 
        - name: POSTGRES_HOST
          value: "negotiator-db"
        - name: NEGOTIATOR_URL
          #value: "https://negotiator.dyn.cloud.e-infra.cz"
          value: "https://negotiator.eucaim.cancerimage.eu"
        - name: AUTH_HOST
          value: "https://login.bbmri-eric.eu"
          #          value: "https://login.bbmri-eric.eu/oidc/authorize"
        - name: AUTH_PUBLIC_KEY
          #          value: "https://login.bbmri-eric.eu/oidc/jwk"
          value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjKvsfThd4XO/J5PDlgnmCZ3vGB8MRwcK4rJ42xO/xVmtwkxV8ZW4LIbRE+uQn4EsyTY8ke9do2sSUHGSIHh6T0OR1nm9eljOEXwO6/kYPJbVvEYRIQaZ5kvuCZEP9dcyHwgaN9thHpo2n71GpVo+kZ/KhUY8XHU7PIUokCPIQrF20CvANa2h8htJMp3mIIBJ2j1sf7qfLo2QAJO5p92zASwPpZSebOFhqU5005Qp7uNB+Rv+1rwL2mclEcXRjmNQmStThOetZLgReoszE3obHyW65UprY269ulKAyqPVm653jtp5aYAt/sP1twgW9UY2+lkOMMpLYwZkTcg3eAW0vQIDAQAB"
          #          value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjKvsfThd4XO/J5PDlgnm
          #      CZ3vGB8MRwcK4rJ42xO/xVmtwkxV8ZW4LIbRE+uQn4EsyTY8ke9do2sSUHGSIHh6
          #      T0OR1nm9eljOEXwO6/kYPJbVvEYRIQaZ5kvuCZEP9dcyHwgaN9thHpo2n71GpVo+
          #      kZ/KhUY8XHU7PIUokCPIQrF20CvANa2h8htJMp3mIIBJ2j1sf7qfLo2QAJO5p92z
          #      ASwPpZSebOFhqU5005Qp7uNB+Rv+1rwL2mclEcXRjmNQmStThOetZLgReoszE3ob
          #      HyW65UprY269ulKAyqPVm653jtp5aYAt/sP1twgW9UY2+lkOMMpLYwZkTcg3eAW0
          #      vQIDAQAB"
        - name: AUTH_CLIENT_ID
          #value: "9a363503-61dc-418b-9da7-8a11e11cccbd"
          value: "a15a95d1-b251-4f12-b608-76ec02c68010"
        - name: AUTH_CLIENT_SECRET
          #value: "O_bG1DZEwhJwzo2YmSou9NTfFF0l-ZZskqwHdY3osz1oQtaJGwip7eS-jDAKu6NiE82JQiLYpMvAa-94riKwOg"
          value: "33a1c16e-fedb-494a-9bdb-fc79fbbb19e63156db50-89ce-46be-ba24-8c8b362f2344"
            #        command: # modified
            #        - /bin/bash
            #        - -c
            #        args:
            #        - sleep 3600
        resources:
          requests:
            cpu: "125m"
            memory: "512Mi"
          limits:
            cpu: "0.2"
            memory: "1Gi"
      volumes:  
      - name: data
        persistentVolumeClaim:
          claimName: negotiator-db-pvc
