kind: PersistentVolume
apiVersion: v1
metadata:
  name: negotiator-db-vol
  labels:
    type: local
spec:
  storageClassName: nfs-negotiator-db
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 150M
  accessModes:
    - ReadWriteMany
  nfs:
    server: X.0.0.X
    path: /mnt/nfs_share/negotiator/db
